/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e8dfee",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#332f39",
        "on-error": "#690005",
        "on-primary-fixed": "#25005a",
        "error": "#ffb4ab",
        "on-tertiary-container": "#76ffc2",
        "secondary": "#4cd7f6",
        "surface-bright": "#3c3742",
        "on-tertiary-fixed": "#002113",
        "surface-container-lowest": "#100d16",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-fixed": "#001f26",
        "secondary-fixed": "#acedff",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-container": "#007650",
        "outline": "#958da1",
        "outline-variant": "#4a4455",
        "inverse-surface": "#e8dfee",
        "surface-container": "#221e28",
        "secondary-container": "#03b5d3",
        "tertiary-fixed-dim": "#4edea3",
        "primary": "#d2bbff",
        "inverse-primary": "#732ee4",
        "surface-dim": "#15121b",
        "tertiary-fixed": "#6ffbbe",
        "error-container": "#93000a",
        "surface-variant": "#37333e",
        "primary-fixed": "#eaddff",
        "surface-container-low": "#1d1a24",
        "surface-tint": "#d2bbff",
        "on-secondary-container": "#00424e",
        "surface-container-high": "#2c2833",
        "secondary-fixed-dim": "#4cd7f6",
        "on-tertiary": "#003824",
        "surface-container-highest": "#37333e",
        "tertiary": "#4edea3",
        "background": "#15121b",
        "on-surface": "#e8dfee",
        "on-primary-container": "#ede0ff",
        "surface": "#15121b",
        "on-surface-variant": "#ccc3d8",
        "primary-container": "#7c3aed",
        "on-primary-fixed-variant": "#5a00c6",
        "primary-fixed-dim": "#d2bbff",
        "on-secondary": "#003640",
        "on-primary": "#3f008e"
      },
      fontFamily: {
        "body-md": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Sora", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "body-sm": ["Sora", "sans-serif"],
        "meta-data": ["Sora", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "meta-data": ["12px", {"lineHeight": "16px", "fontWeight": "400"}]
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "margin-sm": "16px",
        "margin-lg": "48px",
      }
    }
  },
  plugins: [],
};
