"""Alembic migration script template."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1894e5176943'
down_revision = '001_phase0_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.CheckConstraint('number BETWEEN 1 AND 8', name='chk_semester_number'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('row_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('faculty_subject_assignments',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('faculty_id', 'subject_id', 'semester_id', name='pk_faculty_subject_assignments')
    )
    op.create_table('student_enrollments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_id', 'subject_id', 'semester_id', name='pk_student_enrollments')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # 1. Indexes on foreign keys for fast lookup:
    # - ix_student_enrollments_student_id: optimizes querying list of subject enrollments for a given student
    # - ix_faculty_subject_assignments_faculty_id: optimizes querying assigned subjects for a given faculty member
    op.create_index('ix_student_enrollments_student_id', 'student_enrollments', ['student_id'], unique=False)
    op.create_index('ix_faculty_subject_assignments_faculty_id', 'faculty_subject_assignments', ['faculty_id'], unique=False)

    # 2. Database Trigger for Audit Log on student_enrollments
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_student_enrollments_trigger()
        RETURNS TRIGGER AS $$
        DECLARE
            v_user_id INTEGER;
            v_old JSONB;
            v_new JSONB;
        BEGIN
            -- Try to retrieve user context from connection parameter (if set by app)
            BEGIN
                v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::integer;
            EXCEPTION WHEN OTHERS THEN
                v_user_id := NULL;
            END;

            IF (TG_OP = 'DELETE') THEN
                v_old := to_jsonb(OLD);
                v_new := NULL;
                INSERT INTO audit_logs(table_name, row_id, action, old_data, new_data, changed_by, changed_at)
                VALUES ('student_enrollments', OLD.student_id || '-' || OLD.subject_id || '-' || OLD.semester_id, 'delete', v_old, v_new, v_user_id, NOW());
                RETURN OLD;
            ELSIF (TG_OP = 'UPDATE') THEN
                v_old := to_jsonb(OLD);
                v_new := to_jsonb(NEW);
                INSERT INTO audit_logs(table_name, row_id, action, old_data, new_data, changed_by, changed_at)
                VALUES ('student_enrollments', NEW.student_id || '-' || NEW.subject_id || '-' || NEW.semester_id, 'update', v_old, v_new, v_user_id, NOW());
                RETURN NEW;
            ELSIF (TG_OP = 'INSERT') THEN
                v_old := NULL;
                v_new := to_jsonb(NEW);
                INSERT INTO audit_logs(table_name, row_id, action, old_data, new_data, changed_by, changed_at)
                VALUES ('student_enrollments', NEW.student_id || '-' || NEW.subject_id || '-' || NEW.semester_id, 'insert', v_old, v_new, v_user_id, NOW());
                RETURN NEW;
            END IF;
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_audit_student_enrollments
        AFTER INSERT OR UPDATE OR DELETE ON student_enrollments
        FOR EACH ROW EXECUTE FUNCTION audit_student_enrollments_trigger();
    """)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('student_enrollments')
    op.drop_table('faculty_subject_assignments')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_table('semesters')
    # Drop triggers and custom indexes
    op.execute("DROP TRIGGER IF EXISTS trg_audit_student_enrollments ON student_enrollments;")
    op.execute("DROP FUNCTION IF EXISTS audit_student_enrollments_trigger();")
    op.drop_index('ix_student_enrollments_student_id', table_name='student_enrollments')
    op.drop_index('ix_faculty_subject_assignments_faculty_id', table_name='faculty_subject_assignments')
    # ### end Alembic commands ###
