"""Alembic migration script template."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e197b97684'
down_revision = '1894e5176943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='chk_timetable_day'),
    sa.CheckConstraint('end_time > start_time', name='chk_timetable_times'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_id'), 'timetable_slots', ['id'], unique=False)
    
    # Enable btree_gist extension for EXCLUDE constraints on non-range types
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")

    # We must construct an IMMUTABLE helper function to construct timestamp ranges from start_time and end_time
    op.execute("""
        CREATE OR REPLACE FUNCTION make_tsrange(start_time TIME, end_time TIME)
        RETURNS tsrange AS $$
        BEGIN
            RETURN tsrange(('2000-01-01 ' || start_time)::timestamp, ('2000-01-01 ' || end_time)::timestamp);
        END;
        $$ LANGUAGE plpgsql IMMUTABLE;
    """)
    
    # Exclude constraint 1: A faculty member cannot be booked for overlapping slots on the same day
    op.execute("""
        ALTER TABLE timetable_slots
        ADD CONSTRAINT uq_faculty_schedule_overlap EXCLUDE USING gist (
            faculty_id WITH =,
            day_of_week WITH =,
            make_tsrange(start_time, end_time) WITH &&
        );
    """)

    # Exclude constraint 2: A room cannot be booked for overlapping slots on the same day
    op.execute("""
        ALTER TABLE timetable_slots
        ADD CONSTRAINT uq_room_schedule_overlap EXCLUDE USING gist (
            room WITH =,
            day_of_week WITH =,
            make_tsrange(start_time, end_time) WITH &&
        );
    """)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE timetable_slots DROP CONSTRAINT IF EXISTS uq_faculty_schedule_overlap;")
    op.execute("ALTER TABLE timetable_slots DROP CONSTRAINT IF EXISTS uq_room_schedule_overlap;")
    op.drop_index(op.f('ix_timetable_slots_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    # ### end Alembic commands ###
